# Generated by Django 2.0.1 on 2018-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qucikstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='words',
            field=models.ManyToManyField(related_name='words', to='qucikstart.Words'),
        ),
    ]
